---
title: "36-315 Lab 10"
author: "Group 13; Kishan Patel, Maxim Sak, Tyler Wellener, Nathan Yoon; kspatel, masak, twellene, nyoon"
date: "Due Friday, April 7th, 2017 (6:30pm)"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---


##  Lab 10:  Static Graphics Group Project

#  Problem 1 {.tabset}

+  Kishan:
+  Max: 
+  Nathan: A junior who is going to be working in New York City at SocGen this summer. 
+  Tyler: A senior Econ/Stats major who has his own Philadelphia 76ers sports analytics podcast. 


#  Problem 2 {.tabset}

+  Complete. 

#  Problem 3 {.tabset}

https://www.kaggle.com/dansbecker/nba-shot-logs

```{r, warning = FALSE, message = FALSE}
shots = read.csv("shot_logs.csv")
nrow(shots)
ncol(shots)
head(shots)
```

## Dataset Description
+  There are 128,069 rows in this dataset. There are 21 columns in this dataset.

## Variable Descriptions
+  `GAME_ID` is a numeric variable that gives every game played a unique ID. 
+  `MATCHUP` is a character variable that gives the date, year, and team matchups. 
+  `LOCATION` is a character variable that states if the game was home or away. 
+  `W` is a string variable that states if the team won or lost. 
+  `FINAL_MARGIN` is a numeric variable that states how much the team won or lost by. 
+  `SHOT_NUMBER` is a numeric variable that states what shot number it is for a particular player during a particular game. 
+  `PERIOD` is a numeric variable that states what quarter it is during the game. 
+  `GAME_CLOCK` is a character variable that states how much time is left in the particular quarter. 
+  `SHOT_CLOCK` is a character variable that states how much time is left on the 24 second shot clock. 
+  `DRIBBLES` is a numeric variable that states the amount of dribbles the player took before they shot. 
+  `TOUCH_TIME` is a numeric variable that states how long the paricular player had the ball before they shot. 
+  `SHOT_DIST` is a numeric variable that states how many feet away from the basket a player shot the ball. 
+  `PTS_TYPE` is a numeric variable that states if the shot was a 2-point or 3-point shot. 
+  `SHOT_RESULT` is a character variable that states if the basket went in or not. 
+  `CLOSEST_DEFENDER` is a character variable that states who the closest defending player to the shot was. 
+  `CLOSEST_DEFENDER_PLAYER_ID` is a numeric variable that gives a corresponding ID To each defensive player. 
+  `CLOSE_DEF_DIST` is a numeric variable that states how many feet away the closest defending player to the shot was. +  `FGM` is a numeric binary variable that states whether or not the shot went in. 
+  `PTS` is a numeric variable that states whether or not the shot was a 2-point field goal, a 3-point field goal, or it didn't go in. 
+  `player_name` is a character variable thats indicates the name of the player that shot the ball. 
+  `player_id` is a numeric variable that gives a corresponding ID to the player that shot the ball. 


#  Problem 4 {.tabset}

+  What is the relationship between distance and whether or not a shot goes in? Is the mid-range shot really as inefficient as everyone says it is?
+  What is the relationship between shot clock and whether or not a shot goes in?
+  What is the relationship between game clock and whether or not a shot goes in?
+  What is the relationship between the closest defender and whether or not a shot goes in? Who are the best defenders in the NBA and who are the worst at disrupting shot attempts?
+  Can a player get "hot" from scoring a lot of baskets in a row?
+  Do players shoot better when they shoot off of the pass or off of the dribble?



#  Problem 5 {.tabset}

## Part A

(a)  What other functions are listed in the help file for `png()`?

The other functions that are listed in the help file for `png()` are `bmp()`, `jpeg()`, and `tiff()`.

## Part B

(b)  How do you control the height and width of images with the `pdf()` function?  What are the units for these parameters?


You control the height and width of images with the `pdf()` function by passing in values to the width and height arguments of the `pdf()` function. The units for these paramters are in inches. 

## Part C

(c)  How do you control the height and width of images with the `png()` function?  What are the default units for these parameters?

You control the height and width of images with the `png()` function by passing in values to the width and height arguments of the function. THe default units for these paramters are pixels. 


## Part D

(d)  What types of images can you save with the `ggsave()` function?  (Hint:  Look at the `device` parameter.)

With the `ggsave()` function, you can save images such as ps, tex (pictex), pdf, tiff, png, bmp and wmf.

## Part E

(e)  What does the `dpi` parameter control in the `ggsave()` function?  What does `dpi` stand for?

The `dpi` parameter controls the raster graphics. It stands for dots per inch. 



